version: '3.9'

x-logging:
  &default-logging
  options:
    max-size: '12m'
    max-file: '5'

services:
  cornerstone:
    build:
      context: .
      target: development
      dockerfile: config/docker/Dockerfile
    ports:
      - ${FLASK_RUN_PORT}:${FLASK_RUN_PORT}
    volumes:
      - .:/code
    container_name: cornerstone-app
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:${FLASK_RUN_PORT}}/"]
      interval: 30s
      timeout: 10s
    env_file:
      - .env
    stdin_open: true
    tty: true
    logging: *default-logging